version: '3.8'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: agro_app
    volumes:
      - ./app:/var/www/html
    networks:
      - agro_net

  web:
    image: nginx:stable-alpine
    container_name: agro_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - ml
    networks:
      - agro_net

  db:
    image: mysql:8.0
    container_name: agro_db
    env_file:
      - .env.docker
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - agro_net

  redis:
    image: redis:7-alpine
    container_name: agro_redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
    networks:
      - agro_net

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: agro_ml
    volumes:
      - ./ml:/usr/src/app
    ports:
      - "5001:5000"
    networks:
      - agro_net

volumes:
  mysql_data:

networks:
  agro_net:
    driver: bridge
